Resolve NPE
java.sql.SQLException: while executing SQL: select * from STOCK_SYMBOL
        at org.apache.calcite.avatica.Helper.createException(Helper.java:39)
        at org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:97)
        at sqlline.Commands.execute(Commands.java:822)
        at sqlline.Commands.sql(Commands.java:732)
        at sqlline.SqlLine.dispatch(SqlLine.java:808)
        at sqlline.SqlLine.begin(SqlLine.java:681)
        at sqlline.SqlLine.start(SqlLine.java:398)
        at sqlline.SqlLine.main(SqlLine.java:292)
Caused by: java.lang.NullPointerException
        at org.apache.calcite.avatica.AvaticaResultSet.<init>(AvaticaResultSet.java:78)
        at org.apache.calcite.avatica.AvaticaJdbc41Factory.newResultSet(AvaticaJdbc41Factory.java:90)
        at org.apache.calcite.avatica.AvaticaConnection.executeQueryInternal(AvaticaConnection.java:414)
        at org.apache.calcite.avatica.AvaticaStatement.executeQueryInternal(AvaticaStatement.java:394)
        at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:377)
        at org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:95)
        ... 6 more